FeriyalWeb/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path, re_path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('profil.urls'), name="index"),
    
]

profil/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.conf.urls.static import static

app_name = 'profil'

urlpatterns = [
    path('', views.beranda, name="beranda"),
    path('<str:lowongan>', views.render_apply, name="lowongan"),
    path('tentangsaya', views.tentangsaya, name="tentangsaya"),
    path('ceritasaya', views.ceritasaya, name="ceritasaya"),
    path('daftarakun', views.daftarakun, name="daftarakun"),
    path('jadwal', views.jadwal, name='jadwal'),
    path('buatjadwal', views.buatjadwal, name='buatjadwal'),
    path('hapusjadwal', views.hapusjadwal, name='hapusjadwal')
] #+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

profil/models.py
from django.db import models

# Create your models here.
class Jadwal(models.Model):
    activity = models.CharField(max_length=200)
    day = models.CharField(max_length=20)
    date = models.DateField()
    time = models.TimeField()
    place = models.CharField(max_length=200)
    category = models.CharField(max_length=200)

profil/forms.py
from django import forms
from .models import Jadwal

class ScheduleForm(forms.Form):
    activity = forms.CharField(label="Nama Kegiatan")
    day = forms.CharField(label="Hari")
    date = forms.DateField(widget=forms.DateInput(attrs={'type' : 'date'}), label="Tanggal")
    time = forms.TimeField(widget=forms.TimeInput(attrs={'type' : 'time'}), label="Jam")
    place = forms.CharField(label="Tempat")
    category = forms.CharField(label="Kategori")

profil/views.py
from django.shortcuts import render, redirect
from .forms import ScheduleForm
from .models import Jadwal

def render_apply(request, lowongan):
    list_lowongan = ["Data Scientist", "Digital Marketer", "Finance Accounting", "Game Developer", "Jurnalist",
                    "Mobile Developer", "Quality Assurance", "UI/UX Designer", "Web Developer"]
    response = {}
    response['lowongan'] = {'nama_lowongan': list_lowongan[int(lowongan)-1]}
    return render(request, "Pendaftaran.html", response)


def beranda(request):
	return render(request, "Beranda.html")

def tentangsaya(request):
	return render(request, "TentangSaya.html")

def ceritasaya(request):
	return render(request, "CeritaSaya.html")

def daftarakun(request):
	return render(request, "DaftarAkun.html")

def jadwal(request):
    response = {}
    jadwall = Jadwal.objects.all()
    response = {
        "jadwall" : jadwall
    }
    return render(request, 'jadwal.html', response)

data = {}

def buatjadwal(request):
    form = ScheduleForm(request.POST or None)
    response = {}
    if(request.method == "POST"):
        if (form.is_valid()):
            activity = request.POST.get("activity")
            day = request.POST.get("day")
            date = request.POST.get("date")
            time = request.POST.get("time")
            place = request.POST.get("place")
            category = request.POST.get("category")
            Jadwal.objects.create(activity=activity, day=day, date=date, time=time, place=place, category=category)
            return redirect('/jadwal')
        else:
            return render(request, 'JadwalForm.html', response)
    else:
        response['form'] = form
        return render(request, 'JadwalForm.html', response)


def hapusjadwal(request):
    Jadwal.objects.all().delete()
    return redirect('/jadwal')

profil/templates/Beranda.html
{% load static %}
<!DOCTYPE html>
<html>
<title>Job Fair</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>

<!-- jQuery Modal -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" />
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
<style>
body,h1,h2,h3,h4,h5,h6,p {font-family: "Raleway", sans-serif}
</style>
<body class="w3-light-grey w3-content" style="max-width:1600px">

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left: 50px; padding-right: 30px;">

  <!-- Header -->
  <header id="portfolio">
    <a href="#"><img src="avatar_g2.jpg" style="width:65px;" class="w3-circle w3-right w3-margin w3-hide-large w3-hover-opacity"></a>
    <span class="w3-button w3-hide-large w3-xxlarge w3-hover-text-grey" onclick="w3_open()"><i class="fa fa-bars"></i></span>
    <div class="w3-container">
    <h1 style="margin-top: 30px;"><b>Job Fair</b></h1>
    <div class="w3-section w3-bottombar w3-padding-16">
      
    </div>
    </div>
  </header>

  <div class="row row-cols-1 row-cols-md-3 g-4">
	  <div class="col">
	    <div class="card h-100">
	    	<a class="img-button" style="cursor: pointer;" href="#ex1" rel="modal:open"><img src="{% static 'images/data-scientist.jpg'%}" style="width: 400px; height: 600px;" class="card-img-top" alt="..."></a>
	      	
	    	<div id="ex1" class="modal">
			  <img src="{% static 'images/data-scientist.jpg'%}" style="width: 410px; height: 610px;" class="card-img-top" alt="...">
			</div>

	    	<div class="card-body">
	        	<h5 class="card-title">Lowongan 1</h5>
	        	<p class="card-text">Data Scientist</p>
	        	<a href="/1"><button type="button" class="btn btn-primary">Apply</button></a>
	    	</div>
	    </div>
	  </div>
	  <div class="col">
	    <div class="card h-100">
	      <a class="img-button" style="cursor: pointer;" href="#ex2" rel="modal:open"><img src="{% static 'images/digital-marketer.jpg'%}" style="width: 400px; height: 600px;" class="card-img-top" alt="..."></a>

	      <div id="ex2" class="modal">
			  <img src="{% static 'images/digital-marketer.jpg'%}" style="width: 410px; height: 610px;" class="card-img-top" alt="...">
			</div>
	      <div class="card-body">
	        <h5 class="card-title">Lowongan 2</h5>
	        <p class="card-text">Digital Marketer</p>
	        <a href="/2"><button type="button" class="btn btn-primary">Apply</button></a>
	      </div>
	    </div>
	  </div>
	  <div class="col">
	    <div class="card h-100">
	      <a class="img-button" style="cursor: pointer;" href="#ex3" rel="modal:open"><img src="{% static 'images/finance-accounting.jpg'%}" style="width: 400px; height: 600px;" class="card-img-top" alt="..."></a>
	      <div id="ex3" class="modal">
			  <img src="{% static 'images/finance-accounting.jpg'%}" style="width: 410px; height: 610px;" class="card-img-top" alt="...">
			</div>
	      <div class="card-body">
	        <h5 class="card-title">Lowongan 3</h5>
	        <p class="card-text">Finance Accounting</p>
	        <a href="/3"><button type="button" class="btn btn-primary">Apply</button></a>
	      </div>
	    </div>
	  </div>
	  <div class="col">
	    <div class="card h-100">
	      <a class="img-button" style="cursor: pointer;" href="#ex4" rel="modal:open"><img src="{% static 'images/game-development.jpg'%}" style="width: 400px; height: 600px;" class="card-img-top" alt="..."></a>
	      <div id="ex4" class="modal">
			  <img src="{% static 'images/game-development.jpg'%}" style="width: 410px; height: 610px;" class="card-img-top" alt="...">
			</div>
	      <div class="card-body">
	        <h5 class="card-title">Lowongan 4</h5>
	        <p class="card-text">Game Developer</p>
	        <a href="/4"><button type="button" class="btn btn-primary">Apply</button></a>
	      </div>
	    </div>
	  </div>
	  <div class="col">
	    <div class="card h-100">
	      <a class="img-button" style="cursor: pointer;" href="#ex5" rel="modal:open"><img src="{% static 'images/jurnalist.jpg'%}" style="width: 400px; height: 600px;" class="card-img-top" alt="..."></a>
	      <div id="ex5" class="modal">
			  <img src="{% static 'images/jurnalist.jpg'%}" style="width: 410px; height: 610px;" class="card-img-top" alt="...">
			</div>
	      <div class="card-body">
	        <h5 class="card-title">Lowongan 5</h5>
	        <p class="card-text">Jurnalist</p>
	        <a href="/5"><button type="button" class="btn btn-primary">Apply</button></a>
	      </div>
	    </div>
	  </div>
	  <div class="col">
	    <div class="card h-100">
	      <a class="img-button" style="cursor: pointer;" href="#ex6" rel="modal:open"><img src="{% static 'images/mobile-development.jpg'%}" style="width: 400px; height: 600px;" class="card-img-top" alt="..."></a>
	      <div id="ex6" class="modal">
			  <img src="{% static 'images/mobile-development.jpg'%}" style="width: 410px; height: 610px;" class="card-img-top" alt="...">
			</div>
	      <div class="card-body">
	        <h5 class="card-title">Lowongan 6</h5>
	        <p class="card-text">Mobile Developer</p>
	        <a href="/6"><button type="button" class="btn btn-primary">Apply</button></a>
	      </div>
	    </div>
	  </div>
	  <div class="col">
	    <div class="card h-100">
	      <a class="img-button" style="cursor: pointer;" href="#ex7" rel="modal:open"><img src="{% static 'images/quality-assurance.jpeg'%}" style="width: 400px; height: 600px;" class="card-img-top" alt="..."></a>
	      <div id="ex7" class="modal">
			  <img src="{% static 'images/quality-assurance.jpeg'%}" style="width: 410px; height: 610px;" class="card-img-top" alt="...">
			</div>
	      <div class="card-body">
	        <h5 class="card-title">Lowongan 7</h5>
	        <p class="card-text">Quality Assurance</p>
	        <a href="/7"><button type="button" class="btn btn-primary">Apply</button></a>
	      </div>
	    </div>
	  </div>
	  <div class="col">
	    <div class="card h-100">
	      <a class="img-button" style="cursor: pointer;" href="#ex8" rel="modal:open"><img src="{% static 'images/ui-ux.jpg'%}" style="width: 400px; height: 600px;" class="card-img-top" alt="..."></a>
	      <div id="ex8" class="modal">
			  <img src="{% static 'images/ui-ux.jpg'%}" style="width: 410px; height: 610px;" class="card-img-top" alt="...">
			</div>
	      <div class="card-body">
	        <h5 class="card-title">Lowongan 8</h5>
	        <p class="card-text">UI/UX Designer</p>
	        <a href="/8"><button type="button" class="btn btn-primary">Apply</button></a>
	      </div>
	    </div>
	  </div>
	  <div class="col">
	    <div class="card h-100">
	      <a class="img-button" style="cursor: pointer;" href="#ex9" rel="modal:open"><img src="{% static 'images/web-developer.jpg'%}" style="width: 400px; height: 600px;" class="card-img-top" alt="..."></a>
	      <div id="ex9" class="modal">
			  <img src="{% static 'images/web-developer.jpg'%}" style="width: 410px; height: 610px;" class="card-img-top" alt="...">
			</div>
	      <div class="card-body">
	        <h5 class="card-title">Lowongan 9</h5>
	        <p class="card-text">Wev Developer</p>
	        <a href="/9"><button type="button" class="btn btn-primary">Apply</button></a>
	      </div>
	    </div>
	  </div>
  </div> 

</div>
<script>
	$('#exampleModal').modal('toggle');
</script>

<!-- end -->
</body>
</html>

profil/templates/CeritaSaya.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Cerita Saya</title>
	{% include "Navbarku.html" %}
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
	<link rel="stylesheet" media="screen" href="https://fontlibrary.org/face/glacial-indifference" type="text/css"/>	<!-- font -->
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<div id="navi">
		</div>
		<script>
			$(function) {
				$("#navi").load("Navbarku.html");});
			}
		</script>
		<p>
			<br>
			<br>
			<br>
			<br>
			<br>
			<br>
			<br>
			<br>
			<br>
			<br>
		</p>
	</div>
	<div id="tentangsaya" class="container" >
		<div class="square-service-block box-lainnya">
			<div class="row">
				<div class="col-4">
				
					<h4 style="font-size: 20px; color:#FF8B00; font-family: GlacialIndifferenceRegular;">CERITA SAYA</h4>
					<br>
					<div class="btn-group-vertical">
					  <button type="button" class="btn btn-warning">Kuliah di Fasilkom</button>
					  <button type="button" class="btn btn-warning">Rindu SMA</button>
					</div>
				</div>
				<div class="ini col-8">
					
				</div>
			</div>
		</div>

	</div>

	<div>
		<p>
			<br><br>
		</p>

		<div id="footeer">
			</div>
		<script>
			$(function) {
				$("#footeer").load("Footer.html");});
			}
		</script>
		{% include "Footer.html" %}
		<br><br>
	</div>
</body>
</html>

profil/templates/Footer.html
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="">
	<script src="https://code.jquery.com/jquery-1.10.2.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


</head>
<body>
<div>
		<p>
			<br><br>
		</p>
		<div id="bawah" class="container" >
			<div class="square-service-block sociallink">
				<div class="row footer">
					<span><a href="https://www.facebook.com/fridai17?hc_ref=ARTW9l0ATeWGWL789re7iVld06NJtfKVf7in-4zf4PYY-h8XwSRhbBnjwPqO0bHu8yg&fref=nf&__xts__[0]=68.ARDSJpp810gdBSWI8GE9g6CxJGt2FhiR9e5gPJBuBfAotE5lod1UMMa61-TxO3UjbkxP5kWXWJgt-J9SvZXF-i0KsbzOdmOhDVgX0IeduCd-npyNAPuJFm-Y7P9PA1Rqy0vc_N2WIAmCVtD-8pr0_3H_7GulkOE01ns6_a1BrGpgRVO3fv_x&__tn__=C-R" target="_blank">
						<i class="fa fa-facebook-f iconsocial" style="font-size:24px; display:inline-block; width: 20px;"></i>
					</a></span>
					<span><a href="https://twitter.com/" target="_blank">
						<i class="fa fa-twitter iconsocial" style="font-size:24px"></i>
					</a></span>
					<span>
					<a href="https://plus.google.com/102883761578163851191" target="_blank">
						<i class="fa fa-google-plus iconsocial" style="font-size:24px"></i>
					</a></span>
					<span>
					<a href="https://www.instagram.com/feriyalbinyahya/" target="_blank">
						<i class="fa fa-instagram iconsocial" style="font-size:24px"></i>
					</a></span>
				</div>
			</div>
		</div>
		<br><br>
	</div>
</body>
</html>

profil/templates/JadwalForm.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Buat Jadwal</title>
	{% include "Navbarku.html" %}
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
	<link rel="stylesheet" media="screen" href="https://fontlibrary.org/face/glacial-indifference" type="text/css"/>	<!-- font -->
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<div id="navi">
		</div>
		<script>
			$(function) {
				$("#navi").load("Navbarku.html");});
			}
		</script>
		<p>
			<br>
			<br>
			<br>
			<br>
			<br>
			<br>
			<br>
			<br>
			<br>
			<br>
		</p>
	</div>
	<div id="tentangsaya" class="container" >
		<div class="square-service-block box-lainnya formulir">
			<div class="row">
				<h3 class="greet">BUAT JADWAL</h3>
				<br>
			</div>
			<div class="row">
				<div class="col-2">
					<img src="https://image.ibb.co/fVfq1z/calendar_1.png" alt="calendar_1" style="width: 70px;">
				</div>
				<div class="col-4">
					<img src="https://image.ibb.co/ma8XEK/list.png" alt="list" style="width: 70px;">
				</div>
			</div>
			<div class="row">
				<br><br><br>
				<form action="#" method="POST" style="font-size: 20px;">
                    {% csrf_token %}
                    {% for field in form %}
                        <span style="display:inline-block; width: 150px;">{{ field.label_tag }}</span><span>{{ field }}</span><br><br>
                    {% endfor %}
                    <input type="submit" value="Submit" class="btn btn-warning" style="color:black;">
                    <a href="{% url 'profil:jadwal' %}" style="padding-left:15px">Lihat Jadwal</a>
                </form>
			</div>
		</div>

	</div>
	<div>
		<p>
			<br><br>
		</p>

		<div id="footeer">
			</div>
		<script>
			$(function) {
				$("#footeer").load("Footer.html");});
			}
		</script>
		{% include "Footer.html" %}
		<br><br>
	</div>


</body>
</html>

profil/templates/Navbar.html
!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="style.css">
	<script src="https://code.jquery.com/jquery-1.10.2.js"></script>

</head>
<body>
	<nav class="navbar navbar-inverse">
	  <div class="container-fluid">
	    <ul class="nav navbar-nav navbar-right">
	      <li><a href="#">Sign Up</a></li>
	      <li><a href="#">Login</a></li>
	    </ul>
	  </div>
	</nav>
</body>

profil/templates/Navbarku.html
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="">
	<script src="https://code.jquery.com/jquery-1.10.2.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


</head>
<body>
	<div>
		<div class="row">
			<div class="col-1">
				<a href="{% url 'profil:beranda' %}"><img src="https://image.ibb.co/dOpFhK/logo.png" alt="logo" class="logo"></a>
			</div>
			<div class="col-3">
				<p></p>
			</div>
			<div class="col-8">
				<br><br>
				<nav class="navbar navbar-inverse navbarku">
				  <div class="container-fluid">
				    <ul class="nav navbar-nav navbar-right">
				      <li><a href="{% url 'profil:tentangsaya' %}">TENTANG SAYA</a></li>
				      <li><a href="{% url 'profil:ceritasaya' %}">CERITA SAYA</a></li>
				      <li><a href="{% url 'profil:daftarakun' %}">DAFTAR AKUN</a></li>
				      <li><a href="{% url 'profil:jadwal' %}">JADWAL SAYA</a></li>
				    </ul>
				  </div>
				</nav> 
			</div>
		</div>
	</div>
</body>
</html>

profil/templates/jadwal.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Jadwal Saya</title>
	{% include "Navbarku.html" %}
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
	<link rel="stylesheet" media="screen" href="https://fontlibrary.org/face/glacial-indifference" type="text/css"/>	<!-- font -->
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<div id="navi">
		</div>
		<script>
			$(function) {
				$("#navi").load("Navbarku.html");});
			}
		</script>
		<p>
			<br>
			<br>
			<br>
			<br>
			<br>
			<br>
			<br>
			<br>
			<br>
			<br>
		</p>
	</div>
	<div id="tentangsaya" class="container" >
		<div class="row">
			<div class="col-2">
				<p></p>
			</div>
			<div class="col-3">
				<span class="label label-warning" style="font-family:  GlacialIndifferenceRegular; color: #FF8B00; background-color: white; font-size: 25px;">JADWAL SAYA</span>
				<a href="{% url 'profil:buatjadwal' %}"><button type="button" class="btn btn-info" style="width: 100px; background-color: #FF8B00; color: white; font-family: GlacialIndifferenceRegular; border-width: 0px;">Buat Jadwal</button></a>
			</div>
		</div>
		<br>
		<div class="row">
			<div class="square-service-block box-lainnya formulir">
				<div class="row">
					<div class="col-5">
		                <table style="width:100%">
		                    {% if jadwall %}
		                    <!--
		                        <tr style="font-size:20px;">
		                            <th>Nama Kegiatan</th>
		                            <th>Hari / Tanggal</th>
		                            <th>Jam</th>
		                            <th>Tempat</th>
		                            <th>Kategori</th>
		                        </tr> -->
		                        {% for jadwal in jadwall %}
		                        	<!--
		                            <tr>
		                                <td>{{ jadwal.activity }}</td>
		                                <td>{{ jadwal.day }} / {{ jadwal.date }}</td> 
		                                <td>{{ jadwal.time }}</td>
		                                <td>{{ jadwal.place }}</td>
		                                <td>{{ jadwal.category }}</td>
		                            </tr> -->
		                            <div class="square-service-block" style="background-color: #EDF878; padding: 10px 10px; border-radius: 10px;">
			                            <h5 style="font-size: 22px; color: grey;">{{ jadwal.activity }}</h5>
			                            <p><span class="glyphicon glyphicon-calendar"></span> {{ jadwal.day }}, {{ jadwal.date }}</p>
			                            <p><span class="glyphicon glyphicon-time"></span> {{ jadwal.time }}</p>
			                            <p><span class="glyphicon glyphicon-home"></span> {{ jadwal.place }}</p>
			                            <p style="font-size: 14px;">{{ jadwal.category }}</p>
			                            
			                        </div>

		                        {% endfor %}

		                        <a href="{% url 'profil:hapusjadwal' %}"><button type="button" class="btn btn-danger">Hapus semua</button></a>

		                    {% else %}
		                    	<br>
		                        <h4>Belum ada agenda yang akan datang.</h4> 
		                    {% endif %}
		                </table>
		                <br>
			        </div>
				    <div class="col-7">
			        	<p></p>
				    </div>
				</div>
			</div>
		</div>
	</div>

	<div>
		<p>
			<br><br>
		</p>

		<div id="footeer">
			</div>
		<script>
			$(function) {
				$("#footeer").load("Footer.html");});
			}
		</script>
		{% include "Footer.html" %}
		<br><br>
	</div>
</body>
</html>